apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-v5n5l
spec:
  clusterName: example
  bootstrap: {}
  version: 1.18.9
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-v5n5l-provider
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-v5n5l-provider
spec:
  private:
    address: 172.17.8.101
    port: 22
  public:
    address: 127.0.0.1
    port: 2222
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: worker
  name: worker-tsb5q
spec:
  clusterName: example
  bootstrap: {}
  version: 1.18.9
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: worker-tsb5q-provider
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: worker-tsb5q-provider
spec:
  private:
    address: 172.17.8.102
    port: 22
  public:
    address: 127.0.0.1
    port: 2200
